name: "Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.sysext }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        release: ['40', '41', '42', '43']
    container:
      image: "quay.io/fedora/fedora:41"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: "Install tools"
        run: |
          dnf install -y \
            git \
            podman \

      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "dnf install into nested container"
        run: |
          podman run --rm -ti "quay.io/fedora/fedora:${release}" bash -c "dnf install -y strace"
        env:
          release: ${{ matrix.release }}
